export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_RECENT_ARTICLE_LIST = 'FETCH_RECENT_ARTICLE_LIST';
export const FETCH_HOT_ARHTICLE_LIST = 'FETCH_HOT_ARHTICLE_LIST';
export const ADD_TO_ARHTICLE_LIST = 'ADD_TO_ARHTICLE_LIST';
export const SEARCH_ARTICLE = 'SEARCH_ARTICLE';

export const FETCH_TAG_LIST = 'FETCH_TAG_LIST';
export const FETCH_TAG = 'FETCH_TAG';

export const FETCH_TOPIC_LIST = 'FETCH_TOPIC_LIST';
export const FETCH_TOPIC = 'FETCH_TOPIC';

export const FETCH_ABOUT = 'FETCH_ABOUT';

export const FETCH_PROFILE = 'FETCH_PROFILE';

export const HIDDEN_NAV = 'HIDDEN_NAV';
export const SHOW_NAV = 'SHOW_NAV';
export const HIDDEN_FOOTER = 'HIDDEN_FOOTER';
export const SHOW_FOOTER = 'SHOW_FOOTER';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
