export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_RECENT_ARTICLE_LIST = 'FETCH_RECENT_ARTICLE_LIST';
export const FETCH_HOT_ARHTICLE_LIST = 'FETCH_HOT_ARHTICLE_LIST';

export const FETCH_TAG_LIST = 'FETCH_TAG_LIST';
export const FETCH_TAG = 'FETCH_TAG';

export const FETCH_TOPIC_LIST = 'FETCH_TOPIC_LIST';
export const FETCH_TOPIC = 'FETCH_TOPIC';

export const FETCH_ABOUT = 'FETCH_ABOUT';

export const FETCH_PROFILE = 'FETCH_PROFILE';
